#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BEZIER_TOLERANCE 0.25f
#define CATMULL_DETAIL 50
#define CIRCULAR_ARC_TOLERANCE 0.1f

#define FLOAT_EPSILON 1e-3f
#define DOUBLE_EPSILON 1e-7

#endif /* ~CONSTANTS_H */